### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by jots** [nim-lang/nimbot#1]
What is the trick to getting this to compile?

$ nim --version
Nim Compiler Version 0.10.2 (2015-01-14) [Linux: amd64]

$ nimble install irc@#head

nimbot/src $ nim c  -d:ssl nimbot.nim

lib/pure/asyncdispatch.nim(1254, 6) Hint: Processing onIrcEvent as an async proc. [User]
nimbot.nim(55, 67) Info: instantiation from here
nimbot.nim(58, 4) Warning: 'nil' statement is deprecated; use an empty 'discard' statement instead [NilStmt]
lib/pure/asyncdispatch.nim(1254, 6) Hint: Processing match as an async proc. [User]
nimbot.nim(98, 0) Info: instantiation from here
lib/core/macros.nim(273, 38) Error: ambiguous identifier: 'Response' -- use a qualifier

**Comment by dom96** [comment]
Can you try using the latest compiler from Git?

**Comment by jots** [comment]
am I compiling it wrong?  Do I need to make a different ".nimble" directory for dev version of Nim?
 $ nimdev --version
Nim Compiler Version 0.10.3 (2015-01-19) [Linux: amd64]
 $ nimdev c  -d:ssl nimbot.nim

nimbot.nim(55, 67) Info: instantiation from here
nimbot.nim(58, 4) Warning: 'nil' statement is deprecated; use an empty 'discard' statement instead [NilStmt]
lib/pure/asyncdispatch.nim(1258, 6) Hint: Processing match as an async proc. [User]
nimbot.nim(98, 0) Info: instantiation from here
lib/core/macros.nim(273, 38) Error: ambiguous identifier: 'Response' -- use a qualifier

**Comment by DTSCode** [comment]
Just got this issue too. Fixed in the irc channel. You need to remove the httpclient module from the import list and write from import httpclient export Response. I'm writing a patch to render Kicks, and have that fix in there. Will push soon.

**Comment by dom96** [comment]
Should be fixed now.
